"""MANTRA Temporal Leakage & Point-in-Time Evaluation Framework."""

from .temporal_model import (
    TemporalModel,
    TemporalSample,
    NullConstantModel,
    SyntheticTemporalTwinEncoder,
    MockTwinEncoder,
    parse_iso_utc,
)
from .hf_encoder import (
    FOMC_STANCE_ID_TO_LABEL,
    FOMC_STANCE_LABEL_TO_ID,
    HuggingFaceTemporalEncoder,
    hash_corpus,
    hash_model_parameters,
    normalize_and_hash_text,
    resolve_git_commit,
)
from .metrics import (
    stationary_block_bootstrap_indices,
    evaluate_competence,
    compute_masking_sensitivity,
    evaluate_behavioral_leakage,
    evaluate_representational_leakage,
    evaluate_economic_effect,
    evaluate_temporal_robustness,
    pareto_coordinates,
)
from .fomc_benchmark import (
    create_toy_fomc_dataset,
    load_fomc_dataset,
    FOMCBenchmark,
    ToyFOMCBenchmark,
    DatasetValidationError,
    validate_temporal_sample,
    validate_dataset,
    parse_task_label,
)
from .experiment_config import (
    load_experiment_config,
    validate_experiment_config,
    validate_benchmark_against_config,
)
from .twin_experiment import TwinExperimentRunner
from .twin_pipeline import (
    CausalIntegrityError,
    build_classifier_from_mlm_encoder,
    create_dose_stream,
    create_token_matched_dose_stream,
    run_baseline_and_smoke_experiment,
    run_continued_pretraining_mlm,
    train_baseline_stance_model,
    train_downstream_classifier,
)

__all__ = [
    "TemporalModel",
    "TemporalSample",
    "NullConstantModel",
    "SyntheticTemporalTwinEncoder",
    "MockTwinEncoder",
    "HuggingFaceTemporalEncoder",
    "FOMC_STANCE_ID_TO_LABEL",
    "FOMC_STANCE_LABEL_TO_ID",
    "hash_model_parameters",
    "normalize_and_hash_text",
    "hash_corpus",
    "resolve_git_commit",
    "parse_iso_utc",
    "stationary_block_bootstrap_indices",
    "evaluate_competence",
    "compute_masking_sensitivity",
    "evaluate_behavioral_leakage",
    "evaluate_representational_leakage",
    "evaluate_economic_effect",
    "evaluate_temporal_robustness",
    "pareto_coordinates",
    "create_toy_fomc_dataset",
    "load_fomc_dataset",
    "FOMCBenchmark",
    "ToyFOMCBenchmark",
    "DatasetValidationError",
    "validate_temporal_sample",
    "validate_dataset",
    "parse_task_label",
    "TwinExperimentRunner",
    "load_experiment_config",
    "validate_experiment_config",
    "validate_benchmark_against_config",
    "CausalIntegrityError",
    "create_token_matched_dose_stream",
    "create_dose_stream",
    "run_continued_pretraining_mlm",
    "build_classifier_from_mlm_encoder",
    "train_downstream_classifier",
    "train_baseline_stance_model",
    "run_baseline_and_smoke_experiment",
]
